[theme]
base = "dark"
primaryColor = "#1428A0"
backgroundColor = "#05071A"
secondaryBackgroundColor = "#0C1232"
textColor = "#F0F2F8"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
